// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Head from "next/head";
import MetaSeo from "metaseo/Metadata";
import { META_DEFAULT_VIEWPORT } from "metaseo";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <MetaSeo config={{
          name: "Demo Meta SEO",
          title: "Demo Meta SEO package",
          keywords: ["demo", "nextjs", "metadata", "seo", "metadata seo"],
          description: "Demo metadata seo with package metaseo",
          disableOg: true,
          viewport: META_DEFAULT_VIEWPORT,
        }} />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
